# Name will show on our github repository
name: NASA Project CI
# Define different triggers that will cause this workflow to run
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
# Define jobs that are supposed to run when events are triggered
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Use Node.js version 16
        uses: actions/setup-node@v3
        with: 
          node-version: '16'
      - run: npm install  
      - run: npm run build --prefix client




